/* Denise M. Gilbert
ASD Term 1303
Project 2
March 14, 2013
json.js Page*/

var json = {
        "recipients": [
			{
				"fname": ["<strong>First Name:</strong>", "Jamie"],
				"lname": ["<strong>Last Name:</strong>", "Gilbert"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-05-10"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "No"],
				"color": ["<strong>Color:</strong>", "Red"],
				"flowers": ["<strong>Flowers:</strong>", "Roses"],
				"foods": ["<strong>Foods:</strong>", "Chinese"],
				"restaurants": ["<strong>Restaurants:</strong>", "China Town"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Stephen"],
				"lname": ["<strong>Last Name:</strong>", "Gilbert"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-06-05"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "No"],
				"color": ["<strong>Color:</strong>", "Orange"],
				"flowers": ["<strong>Flowers:</strong>", "NA"],
				"foods": ["<strong>Foods:</strong>", "Thai"],
				"restaurants": ["<strong>Restaurants:</strong>", "Downtown Thai"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Damian"],
				"lname": ["<strong>Last Name:</strong>", "Gilbert"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-07-29"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "No"],
				"color": ["<strong>Color:</strong>", "Green"],
				"flowers": ["<strong>Flowers:</strong>", "NA"],
				"foods": ["<strong>Foods:</strong>", "Pizza"],
				"restaurants": ["<strong>Restaurants:</strong>", "Frank's Pizza"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Goodie"],
				"lname": ["<strong>Last Name:</strong>", "TwoShoes"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-08-29"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"color": ["<strong>Color:</strong>", "Brown"],
				"flowers": ["<strong>Flowers:</strong>", "Tulips"],
				"foods": ["<strong>Foods:</strong>", "Spaghetti"],
				"restaurants": ["<strong>Restaurants:</strong>", "Olive Garden"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Green"],
				"lname": ["<strong>Last Name:</strong>", "Jeans"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-01-02"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "No"],
				"color": ["<strong>Color:</strong>", "Black"],
				"flowers": ["<strong>Flowers:</strong>", "Carnations"],
				"foods": ["<strong>Foods:</strong>", "Pot Roast"],
				"restaurants": ["<strong>Restaurants:</strong>", "Homestyle"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Jane"],
				"lname": ["<strong>Last Name:</strong>", "Doe"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-04-08"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "Yes"],
				"color": ["<strong>Color:</strong>", "Purple"],
				"flowers": ["<strong>Flowers:</strong>", "Orchids"],
				"foods": ["<strong>Foods:</strong>", "Italian"],
				"restaurants": ["<strong>Restaurants:</strong>", "Giovanni's"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Lilly"],
				"lname": ["<strong>Last Name:</strong>", "Valley"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-07-10"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "Yes"],
				"color": ["<strong>Color:</strong>", "White"],
				"flowers": ["<strong>Flowers:</strong>", "Petunia"],
				"foods": ["<strong>Foods:</strong>", "Sweets"],
				"restaurants": ["<strong>Restaurants:</strong>", "Bakery One"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Orange"],
				"lname": ["<strong>Last Name:</strong>", "Peel"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-12-10"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "Yes"],
				"color": ["<strong>Color:</strong>", "Blue"],
				"flowers": ["<strong>Flowers:</strong>", "NA"],
				"foods": ["<strong>Foods:</strong>", "Fruit"],
				"restaurants": ["<strong>Restaurants:</strong>", "Home Run Inn"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Henny"],
				"lname": ["<strong>Last Name:</strong>", "Penny"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-08-12"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "Yes"],
				"color": ["<strong>Color:</strong>", "Green"],
				"flowers": ["<strong>Flowers:</strong>", "Roses"],
				"foods": ["<strong>Foods:</strong>", "Fast Foods"],
				"restaurants": ["<strong>Restaurants:</strong>", "Burger King"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "John"],
				"lname": ["<strong>Last Name:</strong>", "Anderson"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-09-15"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "No"],
				"color": ["<strong>Color:</strong>", "Yellow"],
				"flowers": ["<strong>Flowers:</strong>", "Lilly"],
				"foods": ["<strong>Foods:</strong>", "Chinese"],
				"restaurants": ["<strong>Restaurants:</strong>", "Chinese Garden"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Fancy"],
				"lname": ["<strong>Last Name:</strong>", "Pants"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-06-24"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "Yes"],
				"color": ["<strong>Color:</strong>", "Orange"],
				"flowers": ["<strong>Flowers:</strong>", "Tulips"],
				"foods": ["<strong>Foods:</strong>", "Casseroles"],
				"restaurants": ["<strong>Restaurants:</strong>", "Mom and Pop's Place"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Darlene"],
				"lname": ["<strong>Last Name:</strong>", "Smith"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-07-20"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "Yes"],
				"color": ["<strong>Color:</strong>", "White"],
				"flowers": ["<strong>Flowers:</strong>", "Roses"],
				"foods": ["<strong>Foods:</strong>", "Cholocate"],
				"restaurants": ["<strong>Restaurants:</strong>", "Gordon's"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Gregg"],
				"lname": ["<strong>Last Name:</strong>", "Johnson"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-11-13"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "No"],
				"color": ["<strong>Color:</strong>", "Purple"],
				"flowers": ["<strong>Flowers:</strong>", "NA"],
				"foods": ["<strong>Foods:</strong>", "Seafood"],
				"restaurants": ["<strong>Restaurants:</strong>", "Red Lobster"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Elizabeth"],
				"lname": ["<strong>Last Name:</strong>", "Baker"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-02-16"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "Yes"],
				"color": ["<strong>Color:</strong>", "Red"],
				"flowers": ["<strong>Flowers:</strong>", "Lilly of the Valley"],
				"foods": ["<strong>Foods:</strong>", "Chile"],
				"restaurants": ["<strong>Restaurants:</strong>", "Chile Master"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Tom"],
				"lname": ["<strong>Last Name:</strong>", "Turkey"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-11-22"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "No"],
				"color": ["<strong>Color:</strong>", "Black"],
				"flowers": ["<strong>Flowers:</strong>", "NA"],
				"foods": ["<strong>Foods:</strong>", "Pumpkin Pie"],
				"restaurants": ["<strong>Restaurants:</strong>", "Turkey Day Inn"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Maria"],
				"lname": ["<strong>Last Name:</strong>", "Gonzalez"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-05-22"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "Yes"],
				"color": ["<strong>Color:</strong>", "Brown"],
				"flowers": ["<strong>Flowers:</strong>", "Orchids"],
				"foods": ["<strong>Foods:</strong>", "Mexican"],
				"restaurants": ["<strong>Restaurants:</strong>", "Mario's"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Angelina"],
				"lname": ["<strong>Last Name:</strong>", "Metz"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-09-29"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "Yes"],
				"color": ["<strong>Color:</strong>", "Red"],
				"flowers": ["<strong>Flowers:</strong>", "Carnations"],
				"foods": ["<strong>Foods:</strong>", "Deep Dish Pizza"],
				"restaurants": ["<strong>Restaurants:</strong>", "Gino's East"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			},
			{
				"fname": ["<strong>First Name:</strong>", "Ben"],
				"lname": ["<strong>Last Name:</strong>", "Lewis"],
				"address1": ["<strong>Address 1:</strong>", "123 Main Street"],
				"address2": ["<strong>Address 2:</strong>", "Lot 123"],
				"city": ["<strong>City:</strong>", "Bridgeview"],
				"state": ["<strong>State:</strong>", "IL"],
				"zipCode": ["<strong>Zip Code:</strong>", "60406"],
				"bday": ["<strong>Birthday:</strong>", "2012-03-29"],
				"sunSign": ["<strong>Zodiac Sign:</strong>", "Leo"],
				"clothing": ["<strong>Clothing Sizes:</strong>", "Medium"],
				"footwear": ["<strong>Shoe Size:</strong>", "10"],
				"jewelry": ["<strong>Ring Size:</strong>", "5"],
				"colors": ["<strong>Favorite Color(s):</strong>", "Blue"],
				"piercedEars": ["<strong>Pierced Ears:</strong>", "No"],
				"color": ["<strong>Color:</strong>", "Blue"],
				"flowers": ["<strong>Flowers:</strong>", "Tulips"],
				"foods": ["<strong>Foods:</strong>", "Meat"],
				"restaurants": ["<strong>Restaurants:</strong>", "Popular Steakhouse"],
				"wishList1": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList2": ["<strong>Wish List Item:</strong>", "Clothes"],
				"wishList3": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList4": ["<strong>Wish List Item:</strong>", "Money"],
				"wishList5": ["<strong>Wish List Item:</strong>", "Money"]
			}
		]
	};